version: '3.4'

services:
  app:
    build:
      dockerfile: Dockerfile.dev
      context: .
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=database
    volumes:
      - ".:/usr/app"
    depends_on:
      - database

  database:
    image: mongo