version: '3.4'

services:
  ts-node-boilerplate:
    image: ts-node-boilerplate
    build:
      dockerfile: Dockerfile.dev
      context: .
    environment:
      NODE_ENV: development
    ports:
      - 3000
      - 9229:9229
    ## set your startup file here
    command: node --inspect=0.0.0.0:9229 index.js