version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile.prod
      context: .
    command: npm start
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=database
    volumes:
      - ".:/usr/app"
    depends_on:
      - database

  database:
    image: mongo